core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.signin, name='login'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('theme/', views.theme, name='theme'),
]

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.index, name='index'),
    path('stock', views.stock, name='stock'),
    path('add', views.add, name='add'),
    path('logs', views.logs, name='logs'),
    path('checkout', views.checkout, name='checkout'),
    path('edit', views.edit, name='edit'),
    path('page', views.page, name='page')
]

parts/urls.py
from django.urls import path

from . import views

app_name = 'parts'

urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('edit', views.edit, name='edit')
]

poopy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('inventory/', include('inventory.urls')),
    path('parts/', include('parts.urls')),
    path('admin/', admin.site.urls),
] 

parts/models.py
from django.db import models

class Category(models.Model):
    category = models.CharField(max_length=64)
    
    def __str__(self):
        return f'{self.category}'
    

class Part(models.Model):
    partname = models.CharField(max_length=100, unique=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    description = models.CharField(max_length=100)
    price = models.FloatField()
    user = models.CharField(max_length=40)
    date = models.DateField()

    @property
    def usd(self):
        return f'${self.price:,.2f}'

    def __str__(self):
        return f'{self.partname} ({self.category}) - {self.description} : ${self.usd}'
    

parts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from core.models import DarkMode
from django.contrib.auth.decorators import login_required
import datetime
from .models import Part, Category
from core.models import DarkMode

# Create your views here.

@login_required
def index(request):
    part_count = Part.objects.count()
    category_count = Category.objects.count()
    theme = DarkMode.objects.filter(user=request.user.username)[0]
    if request.method == 'POST':      
        part_name = request.POST['part_name'].title()
        if not part_name:
            return render(request, 'parts/index.html', {
                'theme': theme,
                'search': 'Could not find part.'
            })
        
        parts = Part.objects.filter(partname__contains=part_name)
        if not parts:
            return render(request, 'parts/index.html', {
                'theme': theme,
                'search': 'Part not found.'
            })

        return render(request, 'parts/index.html', {
                'theme': theme,
                'parts': parts
            })
    
    return render(request, 'parts/index.html', {
        'theme': theme,
        'part_count': part_count,
        'category_count': category_count
    })

# Create new part
@login_required
def add(request):
    theme = DarkMode.objects.filter(user=request.user.username)[0]
    if request.method == 'POST':
        try:
            price = float(request.POST['price'])
        except ValueError:
            return render(request, 'parts/add.html', {
                'fail': 'Need to fill out everything.',
                'theme': theme
            })
        
        part = request.POST['part'].title()
        category = request.POST['category'].title()
        description = request.POST['description'].capitalize()
        user_submitting = request.user.username
        date = datetime.date.today()

        if not part or not category or not price or not description or not user_submitting or not date:
            return render(request, 'parts/add.html', {
                'fail': 'Need to fill out everything.',
                'theme': theme
            })
        
        category_data = Category.objects.filter(category=category)
        partdata = Part.objects.filter(partname=part)
        if category_data.exists():
            if Part.objects.filter(partname=part).exists():
                return render(request, 'parts/add.html', {
                    'fail': 'Part already exists',
                    'theme': theme
                })
            else:
                Part.objects.create(
                    partname = part,
                    category = category_data.first(),
                    description = description,
                    price = price,
                    user = user_submitting,
                    date = date,
                )
        else:      
            if partdata.exists():
                return render(request, 'parts/add.html', {
                    'fail': 'Category has been created, but part already exists..',
                    'theme': theme
                })
            else:
                Category.objects.create(category=category)
                Part.objects.create(
                    partname = part,
                    category = Category.objects.get(category=category),
                    description = description,
                    price = price,
                    user = user_submitting,
                    date = date,
                )

        return render(request, 'parts/add.html', {
            'success': 'Part information saved!',
            'theme': theme
        })
    
    else: 
        return render(request, 'parts/add.html', {
            'theme': theme
        })


# Edit parts    
@login_required
def edit(request):
    theme = DarkMode.objects.filter(user=request.user.username)[0]
    if request.method == 'POST' and 'search' in request.POST:      
        part_name = request.POST['part_name'].title()
        if not part_name:
            return render(request, 'parts/edit.html', {
                'theme': theme,
                'search': 'Could not find part.'
            })
        
    
        parts = Part.objects.filter(partname__contains=part_name)
        if not parts:
            return render(request, 'parts/edit.html', {
                'theme': theme,
                'search': 'Part not found.'
            })

        return render(request, 'parts/edit.html', {
                'theme': theme,
                'parts': parts
            })
        
    if request.method == 'POST' and 'edit' in request.POST:
        part = request.POST['part'].title()
        name = request.POST['name'].title()
        category = request.POST['category'].title()
        if not part or not name or not category:
            return render(request, 'parts/edit.html', {
                'theme': theme,
                'fail': 'Need to fill out everything.'
            })
        
        try:
            price = float(request.POST['price'])
        except ValueError:
            return render(request, 'parts/edit.html', {
                'theme': theme,
                'fail': 'Failed to input valid price.'
            })
        
        try:
            part_data = Part.objects.get(partname=part)
        except:
            return render(request, 'parts/edit.html', {
                'theme': theme,
                'fail': 'Part not found.'
            })
        
        message = ''
        try:
            category_data = Category.objects.get(category=category)
        except:
            category_data = Category.objects.create(category=category)
            message += 'New category was created. '
        
        part_data.partname = name
        part_data.category = category_data
        part_data.price = price
        part_data.save()

        return render(request, 'parts/edit.html', {
            'theme': theme,
            'success': message + 'Part updated.'
        })
   
    else:
        return render(request, 'parts/edit.html', {
            'theme': theme
        })

parts/templates/parts/add.html
{% extends 'core/base.html' %}
{% block title %}Create{% endblock %}
{% block background %}{{ theme.body }}{% endblock %}
{% block nav %}{{ theme.nav }}{% endblock %}
{% block hover1 %}{{ theme.hover }}{% endblock %}
{% block hover2 %}{{ theme.hover }}{% endblock %}
{% block hover3 %}{{ theme.hover }}{% endblock %}
{% block hover4 %}{{ theme.hover }}{% endblock %}
{% block hover5 %}{{ theme.hover }}{% endblock %}
{% block hover6 %}{{ theme.hover }}{% endblock %}
{% block hover7 %}{{ theme.hover }}{% endblock %}
{% block body %}
<div class="max-sm:w-3/4 mx-auto py-16">
    <div class="text-4xl text-center font-bold py-2">Create new part.</div>
    <p class="text-center text-sm py-2">Here you are creating a new part and storing its information into the database.</p>
</div>
<div class="max-w-md mx-auto py-8 px-6 box-border">
    <div class=" {% if theme.mode == 'Light' %} bg-slate-200 {% else %} bg-zinc-800 {% endif %} rounded-lg">
        <form action="{% url 'parts:add' %}" method="post" class="p-16 mx-auto">
            {% csrf_token %}
            <div class="mb-4">
                <label for="part" class="block font-bold text-sm mb-2 ">Part</label>
                <input type="text" placeholder="Part name" autcomplete="off" name="part" autofocus class="py-2 px-3 text-gray-700 w-full shadow appearance-none border leading-tight rounded focus:outline-none">
            </div>
            
            <div class="mb-4">
                <label for="category" class="block font-bold text-sm mb-2 ">Category</label>
                <input type="text" placeholder="Category" autocomplete="off" name="category" class="py-2 px-3 text-gray-700 w-full shadow appearance-none border leading-tight rounded focus:outline-none">
            </div>
            <div class="mb-4">
                <label for="price" class="block font-bold text-sm mb-2 ">Price</label>
                <input type="text" placeholder="Price" autocomplete="off" name="price" class="py-2 px-3 text-gray-700 w-full shadow appearance-none border leading-tight rounded focus:outline-none">
            </div>
            <div class="mb-4">
                <label for="description" class="block font-bold text-sm mb-2 ">Description</label>
                <input type="text" placeholder="Small description" autocomplete="off" name="description" class="py-2 px-3 text-gray-700 w-full shadow appearance-none border leading-tight rounded focus:outline-none">
            </div>
            <div class="flex justify-center">
                <button type="submit" class="mt-4 w-1/2 shadow bg-gradient-to-r from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded transition ease-in-out delay-150">Submit</button>
            </div>
            {% if fail %}
            <div class="block">
                <p class="text-rose-600 text-sm text-center font-bold mt-4" type="submit">{{ fail }}</p>
            </div>
            {% elif success %}
            <div class="block">
                <p class="text-emerald-500 text-sm text-center font-bold mt-4" type="submit">{{ success }}</p>
            </div>
            {% endif %}
            
        </form>
    </div>
</div>

<div class="max-sm:w-10/12 w-3/4 mx-auto py-16">
    <div class="block text-4xl text-center font-bold py-2">Some other options:</div>
</div>

<div class="w-10/12 2xl:w-4/6 mx-auto pt-12 min-[680px]:py-4">
    <div class="block w-full min-[680px]:flex min-[680px]:flex-row min-[680px]:space-x-6 2xl:space-x-14">
        <a href="{% url 'inventory:add' %}" class="block basis-1/2 h-40 my-8 min-[680px]:my-0 lg:h-60 2xl:h-80 {% if theme.mode == 'Dark' %} bg-zinc-800 hover:bg-zinc-700 drop-shadow-sm {% else %} bg-slate-200 hover:bg-slate-400 drop-shadow-sm {% endif %} rounded-md hover:rounded-lg">
            <div class="flex h-full">
                <div class="m-auto text-2xl min-[680px]:text-3xl font-semibold p-8">Add inventory.</div>
            </div>
        </a>
        <a href="{% url 'inventory:checkout' %}" class="block basis-1/2 h-40 my-8 min-[680px]:my-0 lg:h-60 2xl:h-80 {% if theme.mode == 'Dark' %} bg-zinc-800 hover:bg-zinc-700 drop-shadow-sm {% else %} bg-slate-200 hover:bg-slate-400 drop-shadow-sm {% endif %} rounded-md hover:rounded-lg">
            <div class="flex h-full">
                <div class="m-auto text-2xl min-[680px]:text-3xl font-semibold p-8">Checkout items.</div>
            </div>
        </a>
    </div>
</div>
{% endblock %}

parts/templates/parts/edit.html
{% extends 'core/base.html' %}
{% block title %}Edit Part{% endblock %}
{% block background %}{{ theme.body }}{% endblock %}
{% block nav %}{{ theme.nav }}{% endblock %}
{% block hover1 %}{{ theme.hover }}{% endblock %}
{% block hover2 %}{{ theme.hover }}{% endblock %}
{% block hover3 %}{{ theme.hover }}{% endblock %}
{% block hover4 %}{{ theme.hover }}{% endblock %}
{% block hover5 %}{{ theme.hover }}{% endblock %}
{% block hover6 %}{{ theme.hover }}{% endblock %}
{% block hover7 %}{{ theme.hover }}{% endblock %}
{% block body %}
<div class="mx-auto py-12 {% if theme.mode == 'Light' %} bg-violet-300 {% else %} bg-zinc-600 {% endif %}">
    <div class="text-4xl text-center font-bold py-2">Edit an item.</div>
    <p class="text-center text-sm py-2">Change information about a part.</p>
    <p class="text-center text-sm py-2">Part Name - Category - Price - are all able to change.</p>
</div>

<div class="min-[1040px]:container mx-auto my-8">
    <form action="{% url 'inventory:edit' %}" method="post" class="text-center">
        {% csrf_token %}
        <input type="text" name="part_name" placeholder="Search for part" autofocus autocomplete="off" class="w-1/2 md:w-7/12 lg:w-10/12 py-2 px-4 rounded text-black">
        <button type="submit" name="search" class="shadow bg-gradient-to-r from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500 focus:shadow-outline focus:outline-none text-white py-2 px-4 rounded transition ease-in-out delay-150">Search</button>
        {% if search %}
        <div>
            <p class="text-rose-600 text-sm text-center font-bold mt-4" type="submit">{{ search }}</p>
        </div>
        {% endif %}
    </form>
</div>

{% if parts %}
<div class="min-[1040px]:container mx-auto my-8 lg:rounded-lg overflow-hidden {% if theme.mode == 'Light' %} bg-slate-400 {% else %} bg-zinc-800 {% endif %}">
    <table class="w-full">
        <thead class="text-sm uppercase m-auto {% if theme.mode == 'Light' %} bg-slate-400 {% else %} bg-zinc-600 {% endif %} ">
            <tr>
                <td class="px-6 py-3 text-center">Part name</td>
                <td class="px-6 py-3 text-center">Category</td>
                <td class="px-6 py-3 text-center">Price</td>
                <td class="px-6 py-3 text-center">User</td>
            </tr>
        </thead>
        <tbody>
            {% for part in parts %}
            <tr>
                <td class="px-6 py-3 text-center">{{ part.partname }}</td>
                <td class="px-6 py-3 text-center">{{ part.category }}</td>
                <td class="px-6 py-3 text-center">{{ part.usd }}</td>
                <td class="px-6 py-3 text-center">{{ part.user }}</td>
            </tr>
            {% endfor %}
        </tbody>
        
    </table>
</div>
{% endif %}

<div class="w-full min-[1040px]:container min-[320px] min-[1040px]:flex mx-auto sm:overflow-hidden sm:rounded-md {% if theme.mode == 'Light' %} min-[1040px]:bg-slate-200 {% else %} min-[1040px]:bg-zinc-600 {% endif %}">
    <div class="flex justify-center mx-auto md:w-1/2 {% if theme.mode == 'Light' %} bg-slate-400 {% else %} bg-zinc-800 {% endif %}">
        <form action="{% url 'inventory:edit' %}" method="post" class="p-16 mx-auto">
            {% csrf_token %}
            <div class="mb-4">
                <label for="part" class="block font-bold mb-2 ">Part you want to change</label>
                <input type="text" placeholder="Part" autcomplete="off" name="part" class="text-xl py-2 px-3 text-gray-700 w-full shadow appearance-none border leading-tight rounded focus:outline-none">
            </div>

            <div class="mb-4">
                <label for="part" class="block font-bold mb-2 ">New Name</label>
                <input type="text" placeholder="Change name" autcomplete="off" name="name" class="text-xl py-2 px-3 text-gray-700 w-full shadow appearance-none border leading-tight rounded focus:outline-none">
            </div>

            <div class="mb-4">
                <label for="part" class="block font-bold mb-2 ">Category</label>
                <input type="text" placeholder="Change category" autcomplete="off" name="category" class="text-xl py-2 px-3 text-gray-700 w-full shadow appearance-none border leading-tight rounded focus:outline-none">
            </div>

            <div class="mb-4">
                <label for="part" class="block font-bold mb-2 ">Price</label>
                <input type="text" placeholder="Change price" autcomplete="off" name="price" class="text-xl py-2 px-3 text-gray-700 w-full shadow appearance-none border leading-tight rounded focus:outline-none">
            </div>
            
            <div class="py-3">
                <button type="submit" name="edit" class="shadow bg-gradient-to-r from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500 focus:shadow-outline focus:outline-none text-white font-bold py-4 px-6 rounded transition ease-in-out delay-150">Submit</button>
            </div>

            {% if fail %}
            <div class="block">
                <p class="text-rose-600 text-sm text-center sm:text-left font-bold mt-4" type="submit">{{ fail }}</p>
            </div>
            {% elif success %}
            <div class="block">
                <p class="text-emerald-500 text-sm text-center sm:text-left font-bold mt-4" type="submit">{{ success }}</p>
            </div>
            {% endif %}
        </form>
    </div>
    <div class="w-10/12 min-[1040px]:w-1/2 m-auto">
        <div class="text-2xl md:text-3xl min-[1040px]:text-4xl font-bold text-center">
           Or <a href="{% url 'inventory:edit' %}" class="text-rose-500 hover:text-rose-800 transition ease-in-out">edit inventory.</a>
        </div>
    </div>
</div>

<div class="container mx-auto py-8 sm:py-16">
    <div class="block text-4xl text-center font-bold py-2">Some other options:</div>
</div>

<div class="w-full min-[1040px]:container mx-auto sm:pt-12 min-[680px]:py-4">
    <div class="block w-full min-[680px]:flex min-[680px]:flex-row min-[680px]:space-x-6 2xl:space-x-14">
        <a href="{% url 'inventory:edit' %}" class="block basis-1/2 h-40 my-8 min-[680px]:my-0 lg:h-60 2xl:h-80 {% if theme.mode == 'Dark' %} bg-zinc-800 hover:bg-zinc-700 drop-shadow-sm {% else %} bg-slate-200 hover:bg-slate-400 drop-shadow-sm {% endif %} rounded-md hover:rounded-lg">
            <div class="flex h-full">
                <div class="m-auto capitalize text-2xl min-[680px]:text-3xl font-semibold p-8">Edit inventory.</div>
            </div>
        </a>
        
        <a href="{% url 'inventory:index' %}" class="block basis-1/2 h-40 my-8 min-[680px]:my-0 lg:h-60 2xl:h-80 {% if theme.mode == 'Dark' %} bg-zinc-800 hover:bg-zinc-700 drop-shadow-sm {% else %} bg-slate-200 hover:bg-slate-400 drop-shadow-sm {% endif %} rounded-md hover:rounded-lg">
            <div class="flex h-full">
                <div class="m-auto capitalize text-2xl min-[680px]:text-3xl font-semibold p-8">Check inventory.</div>
            </div>
        </a>
    </div>
</div>
{% endblock %}

parts/templates/parts/index.html
{% extends 'core/base.html' %}
{% block title %}Parts{% endblock %}
{% block background %}{{ theme.body }}{% endblock %}
{% block nav %}{{ theme.nav }}{% endblock %}
{% block hover1 %}{{ theme.hover }}{% endblock %}
{% block hover2 %}{{ theme.hover }}{% endblock %}
{% block hover3 %}{{ theme.hover }}{% endblock %}
{% block hover4 %}{{ theme.hover }}{% endblock %}
{% block hover5 %}{{ theme.hover }}{% endblock %}
{% block hover6 %}{{ theme.hover }}{% endblock %}
{% block hover7 %}{{ theme.hover }}{% endblock %}
{% block body %}
<div class=" mx-auto py-12">
    <div class="text-4xl lg:text-7xl text-center font-bold mt-20 ">The home for all parts.</div>
    <p class="text-center py-6">Search through parts that are saved.</p>
</div>

<div class="min-[1040px]:container mx-auto my-4">
    <form action="{% url 'parts:index' %}" method="post" class="text-center">
        {% csrf_token %}
        <div class="w-10/12 flex mx-auto">
            <input type="text" name="part_name" placeholder="Search with a part name or category" autofocus autocomplete="off" class="w-full py-3 pl-6 pr-40 rounded-full text-black outline-none">
            <button type="submit" name="search" class="-ml-20 shadow bg-gradient-to-r from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500 focus:shadow-outline focus:outline-none text-white py-3 px-5 rounded-r-full transition ease-in-out delay-150">Search</button>
        </div>
        {% if search %}
        <div class="mt-16 mb-28">
            <p class="text-rose-600 text-sm text-center font-bold" type="submit">{{ search }}</p>
        </div>
        {% endif %}
    </form>
</div>

{% if parts %}
<div class="min-[1040px]:container mx-auto my-8 lg:rounded-lg overflow-hidden {% if theme.mode == 'Light' %} bg-slate-200 {% else %} bg-zinc-800 {% endif %}">
    <table class="w-full">
        <thead class="text-sm uppercase m-auto {% if theme.mode == 'Light' %} bg-slate-400 {% else %} bg-zinc-600 {% endif %} ">
            <tr>
                <td class="px-6 py-3 text-center">Part name</td>
                <td class="px-6 py-3 text-center">Category</td>
                <td class="px-6 py-3 text-center">Price</td>
                <td class="px-6 py-3 text-center">User</td>
            </tr>
        </thead>
        <tbody>
            {% for part in parts %}
            <tr>
                <td class="px-6 py-3 text-center">{{ part.partname }}</td>
                <td class="px-6 py-3 text-center">{{ part.category }}</td>
                <td class="px-6 py-3 text-center">{{ part.usd }}</td>
                <td class="px-6 py-3 text-center">{{ part.user }}</td>
            </tr>
            {% endfor %}
        </tbody>
        
    </table>
</div>
{% endif %}

{% if part_count %}
<div class="container mx-auto text-center my-20">
    <div class="text-lg md:text-2xl px-2">
        There is currently <span class="text-rose-600 md:text-3xl">{{ part_count }}</span> different parts with <span class="text-rose-600 md:text-3xl">{{ category_count }}</span> different categories.
    </div>
</div>
{% endif %}




<div class="full mx-auto py-8 sm:py-16 {% if theme.mode == 'Dark' %} bg-zinc-800 drop-shadow-md {% else %} bg-slate-400 drop-shadow-md {% endif %}" >
    <div class="block text-3xl sm:text-4xl text-center font-bold py-2">Things you can do:</div>
    <div class="w-10/12 lg:w-full sm:pt-12 lg:py-8 min-[1040px]:container mx-auto">
        <div class="block w-full lg:flex lg:flex-row lg:space-x-6 2xl:space-x-14">
            <a href="{% url 'inventory:edit' %}" class="block basis-1/2 h-72 my-8 lg:my-0 lg:rounded-xl 2xl:h-80 transition ease-in-out {% if theme.mode == 'Dark' %} bg-zinc-900 hover:bg-zinc-700 drop-shadow-md {% else %} bg-slate-300 hover:bg-slate-200 drop-shadow-md {% endif %}">
                <div class="flex h-full">
                    <div class="m-auto capitalize text-2xl lg:text-3xl font-semibold p-8">Add parts.</div>
                </div>
            </a>
            
            <a href="{% url 'inventory:index' %}" class="block basis-1/2 h-72 my-8 lg:my-0 lg:rounded-xl 2xl:h-80 transition ease-in-out {% if theme.mode == 'Dark' %} bg-zinc-900 hover:bg-zinc-700 drop-shadow-md {% else %} bg-slate-300 hover:bg-slate-200 drop-shadow-md {% endif %}">
                <div class="flex h-full">
                    <div class="m-auto capitalize text-2xl lg:text-3xl font-semibold p-8">Edit parts.</div>
                </div>
            </a>
        </div>
    </div>
</div>


{% endblock %}