core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.signin, name='login'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('theme/', views.theme, name='theme'),
]

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.index, name='index'),
    path('stock', views.stock, name='stock'),
    path('add', views.add, name='add'),
    path('logs', views.logs, name='logs'),
    path('checkout', views.checkout, name='checkout'),
    path('edit', views.edit, name='edit'),
    path('page', views.page, name='page')
]

parts/urls.py
from django.urls import path

from . import views

app_name = 'parts'

urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('edit', views.edit, name='edit')
]

poopy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('inventory/', include('inventory.urls')),
    path('parts/', include('parts.urls')),
    path('admin/', admin.site.urls),
] 

core/models.py
from django.db import models

# Create your models here.
class DarkMode(models.Model):
    user = models.CharField(max_length=64)
    mode = models.CharField(max_length=64, default='Light')
    body = models.CharField(max_length=64, default='bg-slate-300 text-slate-800')
    nav = models.CharField(max_length=64, default='drop-shadow-sm bg-slate-200')
    hover = models.CharField(max_length=64, default='hover:bg-slate-700 hover:text-slate-200')

    def __self__(self):
        return self.mode

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .models import DarkMode
from django.contrib.auth.decorators import login_required
import datetime


@login_required
def index(request):
    today = datetime.date.today()
    # If user has a theme load theme else create default theme
    theme = DarkMode.objects.filter(user=request.user.username)
    if not theme:
        theme = DarkMode.objects.create(user=request.user.username)
        return render(request, 'core/index.html', {
            'theme': theme,
            'date': today
        })
    
    return render(request, 'core/index.html', {
        'theme': theme.first(),
        'date': today
    })
    

def signin(request):
    theme = {
        'body': 'bg-slate-300 text-slate-800',
        'nav': 'drop-shadow-sm bg-slate-200',
        'hover': 'hover:bg-slate-700 hover:text-slate-200',
        'mode': 'Light'
    }
    if request.method == 'POST':
        username = request.POST['username'].title()
        password = request.POST['password']

        # Check that user filled out both username and password
        if not username or not password:
            return render(request, 'core/login.html', {
                'fail': 'Please fill out both Username and Password.',
                'theme': theme
            })
        
        # Check if user in database
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            return render(request, 'core/login.html', {
                'fail': 'Could not find Username and Password. Try again.',
                'theme': theme
            })

    return render(request, 'core/login.html', {
        'theme': theme
    })


def signup(request):
    theme = {
        'body': 'bg-slate-300 text-slate-800',
        'nav': 'drop-shadow-sm bg-slate-200',
        'hover': 'hover:bg-slate-700 hover:text-slate-200',
        'mode': 'Light'
    }
    if request.method == 'POST':
        username = request.POST['username'].title()
        email = request.POST['email']
        password = request.POST['password']
        confirmation = request.POST['confirmation']

        # Check that user filled out form correctly and username available
        if not username or not email or not password or not confirmation:
            return render(request, 'core/signup.html', {
                'fail': 'Please fill out everything.',
                'theme': theme
            })
        
        if password != confirmation:
            return render(request, 'core/signup.html', {
                'fail': 'Passwords do not match.',
                'theme': theme
            })
        
        if User.objects.filter(username=username).exists():
            return render(request, 'core/signup.html', {
                'fail': 'Username already taken',
                'theme': theme
            })
        
        # Create user
        user = User.objects.create_user(username, email, password)
        user.save()
        return render(request, 'core/login.html', {
                'success': 'Successfully signed up',
                'theme': theme
            })

    return render(request, 'core/signup.html', {
        'theme': theme
    })


def signout(request):
    logout(request)
    return redirect('/')


def theme(request):
    # Get the mode user has selected and change colors accordingly
    mode = request.GET.get('mode')

    try:
        theme = DarkMode.objects.get(user=request.user.username)
    except:
        theme = DarkMode.objects.filter(user=request.user.username)[0]

    if mode == 'Dark':
        theme.mode = 'Dark'
        theme.body = 'bg-zinc-900 text-white'
        theme.nav = 'drop-shadow-xl bg-zinc-800'
        theme.hover = 'hover:bg-gray-200 hover:text-gray-900'
        theme.save()

    elif mode == 'Light':
        theme.mode = 'Light'
        theme.body = 'bg-slate-300 text-slate-800'
        theme.nav = 'drop-shadow-sm bg-slate-200'
        theme.hover = 'hover:bg-slate-700 hover:text-slate-200'
        theme.save()

    return redirect('/')

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="min-h-screen p-0 m-0 font-mono {% block background %}{% endblock %}">
    {% if user.is_authenticated %}
    <header class="{% block nav %}{% endblock %} py-6 px-6">
        <div class="flex flex-row">
            <div class="basis-1/4 flex">
                <a href="/" class="text-xl font-semibold ml-3 mt-2 justify-start">PBJ</a>
            </div>
            
            <div class="basis-3/4 min-[1200px]:basis-1/2">
                <div class="lg:space-x-6 flex justify-end min-[1200px]:justify-center">
                    <a href="{% url 'inventory:index' %}" class="rounded-lg px-3 py-2 font-semibold {% block hover3 %}{% endblock %} transition ease-in-out">Inventory</a>
                    <a href="{% url 'parts:index' %}" class="hidden min-[780px]:inline-flex rounded-lg px-3 py-2 font-semibold {% block hover4 %}{% endblock %} transition ease-in-out">Parts</a>
                    <a href="{% url 'inventory:logs' %}" class="hidden min-[780px]:inline-flex rounded-lg px-3 py-2 font-semibold {% block hover5 %}{% endblock %} transition ease-in-out">Logs</a>
                    <a href="{% url 'inventory:checkout' %}" class="hidden min-[780px]:inline-flex rounded-lg px-3 py-2 font-semibold {% block hover7 %}{% endblock %} transition ease-in-out">Checkout</a>
                    <a href="{% url 'core:signout' %}" class="rounded-lg px-3 py-2 font-semibold {% block hover6 %}{% endblock %} transition ease-in-out">Sign Out</a>
                </div>
            </div>

            <div class="hidden justify-end min-[1200px]:basis-1/4 min-[1200px]:flex min-[1200px]:justify-end">
                <div class="lg:space-x-6 flex  ">
                    <a href="/theme?mode=Dark" class=" rounded-lg px-3 py-2 font-light {% block hover1 %}{% endblock %} transition ease-in-out">Dark Mode</a>
                    <a href="/theme?mode=Light" class=" rounded-lg px-3 py-2 font-light {% block hover2 %}{% endblock %} transition ease-in-out">Light Mode</a>
                </div>
            </div>
        </div>
    </header>
    <main>
        {% block body %}
        {% endblock %}
    </main>
    {% else %}
    <div class="absolute top-10 left-10">
        <a href="/" class="text-2xl font-semibold">PBJ</a>
    </div>
    <main class="h-screen">
        {% block nobody %}
        {% endblock %}
    </main>

    {% endif %}

    {% if user.is_authenticated %}
    <footer class="p-10 text-base leading-10 w-full">
        <div class="flex justify-end ">
            <a href="{% url 'core:index' %}" class="font-bold text-base">Created By PoopyButtJ</a>
        </div>
    </footer>
    {% else %}
    <footer class="absolute bottom-6 text-base leading-10 w-full">
        <div class="mx-6">
            <div class="font-semibold text-end">Created By PoopyButtJ</div>
        </div>
    </footer>
    {% endif %} 
        
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}Home{% endblock %}
{% block background %}{{ theme.body }}{% endblock %}
{% block nav %}{{ theme.nav }}{% endblock %}
{% block hover1 %}{{ theme.hover }}{% endblock %}
{% block hover2 %}{{ theme.hover }}{% endblock %}
{% block hover3 %}{{ theme.hover }}{% endblock %}
{% block hover4 %}{{ theme.hover }}{% endblock %}
{% block hover5 %}{{ theme.hover }}{% endblock %}
{% block hover6 %}{{ theme.hover }}{% endblock %}
{% block hover7 %}{{ theme.hover }}{% endblock %}

{% block body %}
<!--BANNER-->
<div class="container mx-auto my-32">
    <h1 class="text-3xl min-[680px]:text-5xl font-semibold text-center">Welcome, {{ request.user.username }}.</h1>
</div>

<div class="hidden min-[680px]:flex flex-row w-10/12 2xl:w-4/6 mx-auto pt-12 min-[680px]:py-4">
    <p class="text-lg w-full font-semibold text-right">{{ date }}</p>
</div>

<!--SECTION-->
<div class="w-10/12 2xl:w-4/6 mx-auto pt-12 min-[680px]:py-4">
    <div class="block w-full min-[680px]:flex min-[680px]:flex-row min-[680px]:space-x-6 2xl:space-x-14">
        <a href="{% url 'inventory:add' %}" class="block basis-1/3 h-40 my-8 min-[680px]:my-0 lg:h-60 2xl:h-80 {% if theme.mode == 'Dark' %} bg-zinc-800 hover:bg-zinc-700 drop-shadow-sm {% else %} bg-slate-200 hover:bg-slate-400 drop-shadow-sm {% endif %} rounded-md hover:rounded-lg">
            <div class="flex h-full font-semibold hover:font-bold">
                <div class="m-auto text-2xl min-[680px]:text-3xl p-8">Add inventory.</div>
            </div>
        </a>
        <a href="{% url 'inventory:checkout' %}" class="block basis-2/3 h-40 my-8 min-[680px]:my-0 lg:h-60 2xl:h-80 {% if theme.mode == 'Dark' %} bg-zinc-800 hover:bg-zinc-700 drop-shadow-sm {% else %} bg-slate-200 hover:bg-slate-400 drop-shadow-sm {% endif %} rounded-md hover:rounded-lg">
            <div class="flex h-full font-semibold hover:font-bold">
                <div class="m-auto text-2xl min-[680px]:text-3xl p-8">Checkout inventory.</div>
            </div>
        </a>
    </div>
</div>

<div class="w-10/12 2xl:w-4/6 mx-auto min-[680px]:py-4">
    <div class="block w-full min-[680px]:flex min-[680px]:flex-row min-[680px]:space-x-6 2xl:space-x-14">
        <a href="{% url 'parts:add' %}" class="block basis-1/4 h-40 my-8 min-[680px]:my-0 lg:h-60 2xl:h-80 {% if theme.mode == 'Dark' %} bg-zinc-800 hover:bg-zinc-700 drop-shadow-sm {% else %} bg-slate-200 hover:bg-slate-400 drop-shadow-sm {% endif %} rounded-md hover:rounded-lg">
            <div class="flex h-full font-semibold hover:font-bold">
                <div class="m-auto text-2xl min-[680px]:text-3xl p-8">Create part.</div>
            </div>
        </a>
        <a href="{% url 'parts:edit' %}" class="block basis-1/4 h-40 my-8 min-[680px]:my-0 lg:h-60 2xl:h-80 {% if theme.mode == 'Dark' %} bg-zinc-800 hover:bg-zinc-700 drop-shadow-sm {% else %} bg-slate-200 hover:bg-slate-400 drop-shadow-sm {% endif %} rounded-md hover:rounded-lg">
            <div class="flex h-full font-semibold hover:font-bold">
                <div class="m-auto text-2xl min-[680px]:text-3xl p-8">Edit parts.</div>
            </div>
        </a>
        <a href="{% url 'inventory:logs' %}" class="block basis-1/2 h-40 my-8 min-[680px]:my-0 lg:h-60 2xl:h-80 {% if theme.mode == 'Dark' %} bg-zinc-800 hover:bg-zinc-700 drop-shadow-sm {% else %} bg-slate-200 hover:bg-slate-400 drop-shadow-sm {% endif %} rounded-md hover:rounded-lg">
            <div class="flex h-full font-semibold hover:font-bold">
                <div class="m-auto text-2xl min-[680px]:text-3xl p-8">Check recent changes made.</div>
            </div>
        </a>
    </div>
</div>

<div class="w-10/12 2xl:w-4/6 mx-auto min-[680px]:py-4">
    <div class="block w-full h-40 my-8 min-[680px]:my-0 lg:h-60 2xl:h-80 {% if theme.mode == 'Dark' %} bg-zinc-800 hover:bg-zinc-700 drop-shadow-sm {% else %} bg-slate-200 hover:bg-slate-400 drop-shadow-sm {% endif %} rounded-md hover:rounded-lg">
        <a href="{% url 'inventory:index' %}">
            <div class="flex h-full font-semibold hover:font-bold">
                <div class="m-auto text-2xl min-[680px]:text-3xl p-8">Search through inventory.</div>
            </div>
        </a>
    </div>
</div>

{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% block title %}Log In{% endblock %}
{% block background %}{{ theme.body }}{% endblock %}
{% block nav %}{{ theme.nav }}{% endblock %}
{% block nobody %}
<div class="flex h-full px-6">
    <div class="m-auto">
        <form method="post" action="{% url 'core:login' %}" class="bg-white shadow-md rounded px-16 pt-16 pb-16 mb-4">
            {% csrf_token %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="username">Username</label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" type="text" placeholder="Username" name="username" autofocus autocomplete="off">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="username">Password</label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" type="password" placeholder="Password" name="password" autocomplete="off">
            </div>
            <div class="pt-2 mb-4">
                <button class="block shadow bg-gradient-to-r from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded transition ease-in-out delay-150" type="submit">Sign In</button>
                <a href="{% url 'core:signup' %}" class="block font-bold text-sm text-zinc-400 hover:text-zinc-500 pt-4 transition ease-in-out">Don't have an account?</a>
            </div>
            {% if fail %}
            <div class="block">
                <p class="text-rose-600 text-sm text-center font-bold mt-4" type="submit">{{ fail }}</p>
            </div>
            {% elif success %}
            <div class="block">
                <p class="text-emerald-500 text-sm text-center font-bold mt-4" type="submit">{{ success }}</p>
            </div>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}
{% block title %}Sign Up{% endblock %}
{% block background %}{{ theme.body }}{% endblock %}
{% block nav %}{{ theme.nav }}{% endblock %}
{% block nobody %}
<div class="flex h-full px-6">
    <div class="m-auto">
        <form method="post" action="{% url 'core:signup' %}" class="bg-white shadow-md rounded p-16 mb-4">
            {% csrf_token %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="username">Username</label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" type="text" placeholder="Username" name="username" autofocus autocomplete="off">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="username">Email</label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" type="email" placeholder="Email" name="email" autocomplete="off">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="username">Password</label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" type="password" placeholder="Password" name="password" autocomplete="off">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="username">Confirmation</label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" type="password" placeholder="Confirmation" name="confirmation" autocomplete="off">
            </div>
            <div class="pt-2 mb-4">
                <button class="block shadow bg-gradient-to-r from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded transition ease-in-out delay-150" type="submit">Sign Up</button>
                <a href="{% url 'core:login' %}" class="block font-bold text-sm text-zinc-400 hover:text-zinc-500 pt-4 transition ease-in-out">Already have an account?</a>
            </div>
            {% if fail %}
            <div class="block">
                <p class="text-rose-600 text-sm text-center font-bold mt-4" type="submit">{{ fail }}</p>
            </div>
            {% elif success %}
            <div class="block">
                <p class="text-emerald-500 text-sm text-center font-bold mt-4" type="submit">{{ success }}</p>
            </div>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}