core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.signin, name='login'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('theme/', views.theme, name='theme'),
]

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.index, name='index'),
    path('stock', views.stock, name='stock'),
    path('add', views.add, name='add'),
    path('logs', views.logs, name='logs'),
    path('checkout', views.checkout, name='checkout'),
    path('edit', views.edit, name='edit'),
    path('page', views.page, name='page')
]

poopy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('inventory/', include('inventory.urls')),
    path('parts/', include('parts.urls')),
    path('admin/', admin.site.urls),
] 

inventory/models.py
from django.db import models

class Inventory(models.Model):
    partname = models.CharField(max_length=100)
    category = models.CharField(max_length=64)
    price = models.FloatField()
    quantity = models.IntegerField()

    def __str__(self):
        return f'{self.partname} ({self.category}) - Qty: {self.quantity} Price: ${self.usd} Total: ${self.total}'

    @property
    def total(self):
        value = self.price * self.quantity
        return f'${value:,.2f}'
    
    @property
    def usd(self):
        return f'${self.price:,.2f}'
    

class Log(models.Model):
    partname = models.CharField(max_length=100)
    category = models.CharField(max_length=64)
    price = models.FloatField()
    quantity = models.IntegerField()
    user = models.CharField(max_length=40)
    date = models.DateTimeField()

    @property
    def total(self):
        value = self.price * self.quantity
        return f'${value:,.2f}'
    
    def __str__(self):
        return f'{self.partname} ({self.category}) - Qty: {self.quantity} Total: ${self.total} User: {self.user} Date: {self.date}'

inventory/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from core.models import DarkMode
from django.contrib.auth.decorators import login_required
import datetime
from .models import Inventory, Log
from parts.models import Part, Category
from core.models import DarkMode
from django.db.models import Sum
import math

# Inventory home
@login_required
def index(request):
    theme = DarkMode.objects.filter(user=request.user.username)[0]
    inventory = Inventory.objects.all()[:20]
    total = 0
    for part in inventory:
        total += part.price * part.quantity

    return render(request, 'inventory/index.html', {
        'theme': theme,
        'inventory': inventory,
        'total': f'${total:,.2f}' 
    })


# Display inventory
@login_required
def stock(request):
    theme = DarkMode.objects.filter(user=request.user.username)[0]
    inventory = Inventory.objects.all().order_by('-quantity')[:10]
    part_count = Inventory.objects.aggregate(Sum('quantity'))
    total = 0
    for part in inventory:
        total += part.price * part.quantity

    # Handles search
    if request.method == 'POST' and 'search' in request.POST:
        part = request.POST['part_name'].title()
        if not part:
            return render(request, 'inventory/stock.html', {
                'theme': theme,
                'inventory': inventory,
                'part_count': part_count,
                'total': f'${total:,.2f}',
                'fail': 'Could not find part.'
            })

        try:
            part_data = Inventory.objects.filter(partname__contains=part)
        except:
            return render(request, 'inventory/stock.html', {
                'theme': theme,
                'inventory': inventory,
                'part_count': part_count,
                'total': f'${total:,.2f}',
                'fail': 'Could not find part.'
            })

        return render(request, 'inventory/stock.html', {
            'theme': theme,
            'inventory': part_data,
            'part_count': part_count,
            'total': f'${total:,.2f}',
            'success': 'success'
        })
    
    return render(request, 'inventory/stock.html', {
        'theme': theme,
        'inventory': inventory,
        'part_count': part_count,
        'total': f'${total:,.2f}'
    })

@login_required
def page(request):
    theme = DarkMode.objects.filter(user=request.user.username)[0]
    parts = Inventory.objects.count()
    pages = math.ceil(parts/10)
    inventory = Inventory.objects.all()[:10]
    if request.method == 'GET':
        return render(request, 'inventory/page.html', {
            'theme': theme,
            'pages': range(1,pages+1),
            'inventory': inventory
        })
    
    if request.method == 'POST':
        try:
            page = int(request.POST['page'])
        except ValueError:
            return render(request, 'inventory/page.html', {
                'fail': 'Page not founds',
                'theme': theme,
                'inventory': inventory,
                'pages': range(1,pages+1),
            })

        if page > pages or page < 0:
            return render(request, 'inventory/page.html', {
                'fail': 'Page not found',
                'theme': theme,
                'inventory': inventory,
                'pages': range(1,pages+1),
            })
        
        inventory = Inventory.objects.all()[page*10-10:page*10]
        return render(request, 'inventory/page.html', {
            'theme': theme,
            'pages': range(1,pages+1),
            'inventory': inventory
        })

            


# Add inventory
@login_required
def add(request):
    theme = DarkMode.objects.filter(user=request.user.username)[0]
    if request.method == 'POST':
        try:
            quantity = int(request.POST['quantity'])
        except ValueError:
            return render(request, 'inventory/add.html', {
                'theme': theme,
                'fail': 'Quantity has to be a whole number.'
            })
        part = request.POST['part'].title()

        if not part or not quantity:
            return render(request, 'inventory/add.html', {
                'theme': theme,
                'fail': 'Need to fill out both parts.'
            })
        
        try:
            partdata = Part.objects.get(partname=part)
        except:
            return render(request, 'inventory/add.html', {
                'theme': theme,
                'fail': 'Part not found.'
            })
        
        # If part in inventory update quantity else create
        if Inventory.objects.filter(partname=part).exists():
            inventory = Inventory.objects.get(partname=part)
            inventory.quantity += quantity
            inventory.save()
        else:
            Inventory.objects.create(
                partname = part,
                category = partdata.category,
                quantity = quantity,
                price = partdata.price
            )
        
        # Create a log entry
        date = datetime.datetime.now()
        user = request.user.username
        Log.objects.create(
            partname = partdata.partname,
            category = partdata.category,
            price = partdata.price,
            quantity = quantity,
            user = user,
            date = date,
        )

        return render(request, 'inventory/add.html', {
            'success': 'Updated inventory!',
            'theme': theme
        })
        
    else:
        return render(request, 'inventory/add.html', {
            'theme': theme
        })
    

# Show logs
@login_required
def logs(request):
    logs = Log.objects.all().order_by('-date')[:15]
    theme = DarkMode.objects.filter(user=request.user.username)[0]
    return render(request, 'inventory/logs.html', {
        'theme': theme,
        'logs': logs,
})


# Checkout parts
@login_required
def checkout(request):
    theme = DarkMode.objects.filter(user=request.user.username)[0]
    if request.method == 'POST':
        part = request.POST['part'].title()
        try:
            quantity = int(request.POST['quantity'])
        except ValueError:
            return render(request, 'inventory/checkout.html', {
                'theme': theme,
                'fail': 'Quantity has to be whole number.'
            })
        
        if not part or not quantity:
            return render(request, 'inventory/checkout.html', {
                'theme': theme,
                'fail': 'Need to fill out both parts.'
            })
        
        try:
            data = Inventory.objects.get(partname=part)
        except:
            return render(request, 'inventory/checkout.html', {
                'theme': theme,
                'fail': 'Part not found'
            })
        
        if quantity > data.quantity:
            return render(request, 'inventory/checkout.html', {
                'theme': theme,
                'fail': 'Not enough in stock.'
            })
        
        data.quantity -= quantity
        data.save()
        date = datetime.datetime.now()
        user = request.user.username

        Log.objects.create(
            partname = data.partname,
            category = data.category,
            price = data.price,
            quantity = -quantity,
            user = user,
            date = date,
        )

        return render(request, 'inventory/checkout.html', {
            'theme': theme,
            'success': 'Checkout complete.'
        })
    
    else:
        return render(request, 'inventory/checkout.html', {
            'theme': theme,
        })
        
    
# Edit inventory    
@login_required
def edit(request):
    theme = DarkMode.objects.filter(user=request.user.username)[0]
    # Handles search
    if request.method == 'POST' and 'search' in request.POST:      
        part_name = request.POST['part_name'].title()
        if not part_name:
            return render(request, 'inventory/edit.html', {
                'theme': theme,
                'search': 'Could not find part.'
            })
    
        part_inventory = Inventory.objects.filter(partname__contains=part_name)
        if not part_inventory:
            return render(request, 'inventory/edit.html', {
                'theme': theme,
                'search': 'Part not found.'
            })

        return render(request, 'inventory/edit.html', {
                'theme': theme,
                'parts': part_inventory
            })

    # Handles changing info   
    if request.method == 'POST' and 'edit' in request.POST:
        try:
            part = request.POST['part'].title()
            name = request.POST['name'].title()
            category = request.POST['category'].title()
            price = float(request.POST['price'])
            if not part or not name or not category or not price:
                return render(request, 'inventory/edit.html', {
                    'theme': theme,
                    'fail': 'Need to fill out everything.'
                })
        except ValueError:
            return render(request, 'inventory/edit.html', {
                'theme': theme,
                'fail': 'Failed to input valid price.'
            })
        
        try:
            part_data = Part.objects.get(partname=part)
        
        except:
            return render(request, 'inventory/edit.html', {
                'theme': theme,
                'fail': 'Part not found.'
            })
        
    else:
        return render(request, 'inventory/edit.html', {
            'theme': theme
        })

inventory/templates/inventory/checkout.html
{% extends 'core/base.html' %}
{% block title %}Checkout{% endblock %}
{% block background %}{{ theme.body }}{% endblock %}
{% block nav %}{{ theme.nav }}{% endblock %}
{% block hover1 %}{{ theme.hover }}{% endblock %}
{% block hover2 %}{{ theme.hover }}{% endblock %}
{% block hover3 %}{{ theme.hover }}{% endblock %}
{% block hover4 %}{{ theme.hover }}{% endblock %}
{% block hover5 %}{{ theme.hover }}{% endblock %}
{% block hover6 %}{{ theme.hover }}{% endblock %}
{% block hover7 %}{{ theme.hover }}{% endblock %}
{% block body %}
<div class="max-sm:w-3/4 mx-auto py-16">
    <div class="text-4xl text-center font-bold py-2">Checkout some parts.</div>
    <p class="text-center text-sm py-2">Need some parts? No worries you can check them out here.</p>
</div>

<div class="max-w-md mx-auto py-8 px-6 box-border">
    <div class=" {% if theme.mode == 'Light' %} bg-slate-200 {% else %} bg-zinc-800 {% endif %} rounded-lg">
        <form action="{% url 'inventory:checkout'%}" method="post" class="p-16 mx-auto">
            {% csrf_token %}
            <div class="mb-4">
                <label for="part" class="block font-bold text-sm mb-2 ">Part</label>
                <input type="text" placeholder="Part" autcomplete="off" autofocus name="part" class="py-2 px-3 text-gray-700 w-full shadow appearance-none border leading-tight rounded focus:outline-none">
            </div>
            
            <div class="mb-4">
                <label for="category" class="block font-bold text-sm mb-2 ">Quantity</label>
                <input type="text" placeholder="Category" autocomplete="off" name="quantity" class="py-2 px-3 text-gray-700 w-full shadow appearance-none border leading-tight rounded focus:outline-none">
            </div>

            <div class="flex justify-center">
                <button type="submit" class="mt-4 w-1/2 shadow bg-gradient-to-r from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded transition ease-in-out delay-150">Submit</button>
            </div>
            {% if fail %}
            <div class="block">
                <p class="text-rose-600 text-sm text-center font-bold mt-4" type="submit">{{ fail }}</p>
            </div>
            {% elif success %}
            <div class="block">
                <p class="text-emerald-500 text-sm text-center font-bold mt-4" type="submit">{{ success }}</p>
            </div>
            {% endif %}
        </form>
    </div>
</div>

<div class="max-sm:w-3/4 mx-auto py-16">
    <div class="text-4xl text-center font-bold py-2">Search for part.</div>
    <p class="text-center text-sm pt-2">Fill below to help you find the name of a part.</p>
    <p class="text-center text-sm py-1">Not everything must be filled but filling more narrows the results.</p>
</div>

<div class="max-w-md mx-auto py-8 px-6 box-border">
    <div class=" {% if theme.mode == 'Light' %} bg-slate-200 {% else %} bg-zinc-800 {% endif %} rounded-lg">
        <form action="" class="p-16 mx-auto">
            <div class="mb-4">
                <label for="part" class="block font-bold text-sm mb-2 ">Part</label>
                <input type="text" placeholder="If you have an idea" autcomplete="off" name="part" class="py-2 px-3 text-gray-700 w-full shadow appearance-none border leading-tight rounded focus:outline-none">
            </div>

            <div class="mb-4">
                <label for="part" class="block font-bold text-sm mb-2 ">Category</label>
                <input type="text" placeholder="Category" autcomplete="off" name="category" class="py-2 px-3 text-gray-700 w-full shadow appearance-none border leading-tight rounded focus:outline-none">
            </div>
            
            <div class="mb-4">
                <label for="category" class="block font-bold text-sm mb-2 ">Descritpion</label>
                <input type="text" placeholder="Description" autocomplete="off" name="description" class="py-2 px-3 text-gray-700 w-full shadow appearance-none border leading-tight rounded focus:outline-none">
            </div>

            <div class="mb-4">
                <label for="price" class="block font-bold text-sm mb-2 ">Price</label>
                <input type="text" placeholder="Price" autocomplete="off" name="price" class="py-2 px-3 text-gray-700 w-full shadow appearance-none border leading-tight rounded focus:outline-none">
            </div>

            <div class="flex justify-center">
                <button type="submit" class="mt-4 w-1/2 shadow bg-gradient-to-r from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded transition ease-in-out delay-150">Submit</button>
            </div>
            
        </form>
    </div>
</div>

<div class="max-sm:w-10/12 w-3/4 mx-auto py-16">
    <div class="block text-4xl text-center font-bold py-2">Some other options:</div>
</div>

<div class="w-10/12 2xl:w-4/6 mx-auto pt-12 min-[680px]:py-4">
    <div class="block w-full min-[680px]:flex min-[680px]:flex-row min-[680px]:space-x-6 2xl:space-x-14">
        <a href="{% url 'inventory:add' %}" class="block basis-1/2 h-40 my-8 min-[680px]:my-0 lg:h-60 2xl:h-80 {% if theme.mode == 'Dark' %} bg-zinc-800 hover:bg-zinc-700 drop-shadow-sm {% else %} bg-slate-200 hover:bg-slate-400 drop-shadow-sm {% endif %} rounded-md hover:rounded-lg">
            <div class="flex h-full">
                <div class="m-auto text-2xl min-[680px]:text-3xl font-semibold p-8">Create Logs.</div>
            </div>
        </a>
        <a href="{% url 'inventory:index' %}" class="block basis-1/2 h-40 my-8 min-[680px]:my-0 lg:h-60 2xl:h-80 {% if theme.mode == 'Dark' %} bg-zinc-800 hover:bg-zinc-700 drop-shadow-sm {% else %} bg-slate-200 hover:bg-slate-400 drop-shadow-sm {% endif %} rounded-md hover:rounded-lg">
            <div class="flex h-full">
                <div class="m-auto text-2xl min-[680px]:text-3xl font-semibold p-8">Check inventory.</div>
            </div>
        </a>
    </div>
</div>
{% endblock %}

inventory/templates/inventory/index.html
{% extends 'core/base.html' %}
{% block title %}Inventory{% endblock %}
{% block background %}{{ theme.body }}{% endblock %}
{% block nav %}{{ theme.nav }}{% endblock %}
{% block hover1 %}{{ theme.hover }}{% endblock %}
{% block hover2 %}{{ theme.hover }}{% endblock %}
{% block hover3 %}{{ theme.hover }}{% endblock %}
{% block hover4 %}{{ theme.hover }}{% endblock %}
{% block hover5 %}{{ theme.hover }}{% endblock %}
{% block hover6 %}{{ theme.hover }}{% endblock %}
{% block hover7 %}{{ theme.hover }}{% endblock %}
{% block body %}
<div class="h-96 flex {% if theme.mode == 'Light' %} bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 {% else %} bg-zinc-700 {% endif %}">
    <div class="m-auto text-center text-2xl lg:text-3xl xl:text-5xl font-bold">
        Find everything to do with inventory here.
    </div>
</div>
<div class="container mx-auto pt-32 pb-10">
    <div class="text-xl sm:text-3xl text-center font-semibold">
        Choose where to start:
    </div>
</div>
<div class="w-10/12 md:w-7/12 lg:w-1/2 xl:w-10/12 2xl:w-7/12 mx-auto py-10">
    <div class=" xl:flex xl:flex-row xl:space-x-12 ">
        <a href="{% url 'inventory:stock' %}" class="xl:basis-1/3 block p-14 my-10 hover:p-16 h-80 {% if theme.mode == 'Light' %} text-slate-100 bg-gradient-to-r from-violet-500 to-blue-500 hover:from-yellow-500 hover:to-pink-500 {% else %} bg-zinc-800 hover:bg-zinc-600 {% endif %} rounded-xl transition ease-in-out delay-150">
            <h1 class="text-2xl font-bold ">Browse inventory</h1>
            <p class="pt-4 ">Browse through parts in inventory. Check and see if the part you're looking for is available.</p>
        </a>
        <a href="{% url 'inventory:checkout' %}" class="xl:basis-1/3 block p-14 my-10 hover:p-16 h-80 {% if theme.mode == 'Light' %} text-slate-100 bg-gradient-to-r from-violet-500 to-blue-500 hover:from-yellow-500 hover:to-pink-500 {% else %} bg-zinc-800 hover:bg-zinc-600 {% endif %} rounded-xl transition ease-in-out delay-150">
            <h1 class="text-2xl font-bold">Checkout inventory</h1>
            <p class="pt-4 ">Remove parts from inventory. Any changes will be logged and available to see later on.</p>
        </a>
        <a href="{% url 'inventory:edit' %}" class="xl:basis-1/3 block p-14 my-10 hover:p-16 h-80 {% if theme.mode == 'Light' %} text-slate-100 bg-gradient-to-r from-violet-500 to-blue-500 hover:from-yellow-500 hover:to-pink-500 {% else %} bg-zinc-800 hover:bg-zinc-600 {% endif %} rounded-xl transition ease-in-out delay-150">
            <h1 class="text-2xl font-bold">Edit inventory</h1>
            <p class="pt-4 ">Change any information of parts in inventory.</p>
        </a>
    </div>
</div>


{% endblock %}

inventory/templates/inventory/logs.html
{% extends 'core/base.html' %}
{% block title %}Logs{% endblock %}
{% block background %}{{ theme.body }}{% endblock %}
{% block nav %}{{ theme.nav }}{% endblock %}
{% block hover1 %}{{ theme.hover }}{% endblock %}
{% block hover2 %}{{ theme.hover }}{% endblock %}
{% block hover3 %}{{ theme.hover }}{% endblock %}
{% block hover4 %}{{ theme.hover }}{% endblock %}
{% block hover5 %}{{ theme.hover }}{% endblock %}
{% block hover6 %}{{ theme.hover }}{% endblock %}
{% block hover7 %}{{ theme.hover }}{% endblock %}
{% block body %}
<div class="container mx-auto">
    <div class="py-40 text-7xl font-bold text-center">
        Checkout some of the recent changes.
    </div>
</div>
<div class="w-10/12 mx-auto block sm:container py-4">
    <div class="sm:flex sm:justify-between sm:space-x-2 md:space-x-3">
        <a href="{% url 'inventory:add' %}" class="block py-20 text-3xl text-center sm:text-base m-auto mt-6 sm:p-4 sm:m-0 w-full font-semibold rounded-md shadow-md {% if theme.mode == 'Light' %} bg-slate-400 hover:bg-slate-200 {% else %} bg-zinc-700 hover:bg-zinc-400 {% endif %} transition ease-in-out">
            Add
        </a>
        <a href="{% url 'inventory:edit' %}" class="block py-20 text-3xl text-center sm:text-base m-auto mt-6 sm:p-4 sm:m-0 w-full font-semibold rounded-md shadow-md {% if theme.mode == 'Light' %} bg-slate-400 hover:bg-slate-200 {% else %} bg-zinc-700 hover:bg-zinc-400 {% endif %} transition ease-in-out">
            Edit
        </a>
        <a href="{% url 'inventory:checkout' %}" class="block py-20 text-3xl text-center sm:text-base m-auto mt-6 sm:p-4 sm:m-0 w-full font-semibold rounded-md shadow-md {% if theme.mode == 'Light' %} bg-slate-400 hover:bg-slate-200 {% else %} bg-zinc-700 hover:bg-zinc-400 {% endif %} transition ease-in-out">
            Checkout
        </a>
        <a href="{% url 'inventory:index' %}" class="block py-20 text-3xl text-center sm:text-base m-auto mt-6 mb-10 sm:mb-0 sm:p-4 sm:m-0 w-full font-semibold rounded-md shadow-md {% if theme.mode == 'Light' %} bg-slate-400 hover:bg-slate-200 {% else %} bg-zinc-700 hover:bg-zinc-400 {% endif %} transition ease-in-out">
            Inventory
        </a>
    </div>
</div>
<section class="container mx-auto">
    <div class="{% if theme.mode == 'Light' %} bg-slate-200 {% else %} bg-zinc-800 {% endif %} rounded-lg">
        <div class="relative shadow-md">
            <div class="overflow-x-auto rounded-lg">
                <table class="w-full text-sm text-left">
                    <thead class="text-xs uppercase m-auto{% if theme.mode == 'Light' %} bg-slate-400 {% else %} bg-zinc-700 {% endif %} ">
                        <tr class="">
                            <td scope="col" class="px-6 py-3 text-center">Product name</td>
                            <td scope="col" class="px-6 py-3 text-center">Category</td>
                            <td scope="col" class="px-6 py-3 text-center">Quantity</td>
                            <td scope="col" class="px-6 py-3 text-center">Price</td>
                            <td scope="col" class="px-6 py-3 text-center">User</td>
                            <td scope="col" class="px-6 py-3 text-center">Date</td>
                        </tr>
                    </thead>

                    <tbody>
                        {% for log in logs %}
                        <tr class="">
                            <td scope="col" class="px-6 py-3 text-center">{{ log.partname }}</td>
                            <td scope="col" class="px-6 py-3 text-center">{{ log.category }}</td>
                            <td scope="col" class="px-6 py-3 text-center">{{ log.quantity }}</td>
                            <td scope="col" class="px-6 py-3 text-center">{{ log.total }}</td>
                            <td scope="col" class="px-6 py-3 text-center">{{ log.user }}</td>
                            <td scope="col" class="px-6 py-3 text-center">{{ log.date }}</td>
                        </tr>
                        {% endfor %}
                        <tr class="">
                            <td scope="col" class="px-6 py-3 text-center">Product name</td>
                            <td scope="col" class="px-6 py-3 text-center">Category</td>
                            <td scope="col" class="px-6 py-3 text-center">Quantity</td>
                            <td scope="col" class="px-6 py-3 text-center">Price</td>
                            <td scope="col" class="px-6 py-3 text-center">Total</td>
                            <td scope="col" class="px-6 py-3 text-center">Total</td>
                        </tr>
                        <tr class="">
                            <td scope="col" class="px-6 py-3 text-center">Product name</td>
                            <td scope="col" class="px-6 py-3 text-center">Category</td>
                            <td scope="col" class="px-6 py-3 text-center">Quantity</td>
                            <td scope="col" class="px-6 py-3 text-center">Price</td>
                            <td scope="col" class="px-6 py-3 text-center">Total</td>
                            <td scope="col" class="px-6 py-3 text-center">Total</td>
                        </tr>
                        <tr class="">
                            <td scope="col" class="px-6 py-3 text-center">Product name</td>
                            <td scope="col" class="px-6 py-3 text-center">Category</td>
                            <td scope="col" class="px-6 py-3 text-center">Quantity</td>
                            <td scope="col" class="px-6 py-3 text-center">Price</td>
                            <td scope="col" class="px-6 py-3 text-center">Total</td>
                            <td scope="col" class="px-6 py-3 text-center">Total</td>
                        </tr>
                        <tr class="">
                            <td scope="col" class="px-6 py-3 text-center">Product name</td>
                            <td scope="col" class="px-6 py-3 text-center">Category</td>
                            <td scope="col" class="px-6 py-3 text-center">Quantity</td>
                            <td scope="col" class="px-6 py-3 text-center">Price</td>
                            <td scope="col" class="px-6 py-3 text-center">Total</td>
                            <td scope="col" class="px-6 py-3 text-center">Total</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}